=== Ano-16/WSD_Lab5/XML/blood_donation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="bloodDonation">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="organization">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="address" type="xs:string"/>
                            <xs:element name="contact" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="donor">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="age">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="18"/>
                                        <xs:maxInclusive value="65"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="bloodType">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="O+"/>
                                        <xs:enumeration value="O-"/>
                                        <xs:enumeration value="A+"/>
                                        <xs:enumeration value="A-"/>
                                        <xs:enumeration value="B+"/>
                                        <xs:enumeration value="B-"/>
                                        <xs:enumeration value="AB+"/>
                                        <xs:enumeration value="AB-"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="donation">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="date" type="xs:date"/>
                            <xs:element name="volume">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="250"/>
                                        <xs:maxInclusive value="500"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Ano-16/WSD_Lab5/XML/blood_donation.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="blood_donation.xsl"?>
<!DOCTYPE bloodDonation [
    <!ENTITY orgName "Red Cross Society">
    <!ENTITY orgAddress "3rd Cross, Further Mahalaxmi Extension">
    <!ENTITY orgContact "021-590059">
    <!ENTITY donorName "Joseph James">
    <!ENTITY donorAge "30">
    <!ENTITY donorBloodType "O+">
    <!ENTITY donationDate "2024-08-07">
    <!ENTITY donationVolume "500">
]>
<bloodDonation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="blood_donation.xsd">
    <organization>
        <name>&orgName;</name>
        <address>&orgAddress;</address>
        <contact>&orgContact;</contact>
    </organization>
    <donor>
        <name>&donorName;</name>
        <age>&donorAge;</age>
        <bloodType>&donorBloodType;</bloodType>
    </donor>
    <donation>
        <date>&donationDate;</date>
        <volume>&donationVolume;</volume>
    </donation>
</bloodDonation>
